#site conf
title: Bretty
description: <span>Bretty</span> is a simple and pretty <span>Jekyll</span> theme.

#user profile
user_name: brittany
twitter: twitter
facebook: facebook
dribbble: dribbble
email: me@example.com

gravatar_HASH: 9240697ab4e6f2fce597da0fa1f43e8e


pygments: true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
